export const BASE_URL = 'http://127.0.0.1:8000/api/v1/'
// export const BASE_URL = 'https://sw-ecommerce-api.up.railway.app/api/v1/'
export const SERVER_URL = 'http://127.0.0.1:8000'
// export const SERVER_URL = 'https://sw-ecommerce-api.up.railway.app'
export const PAYPAL_CLIENT_ID = 'AaRQUWbAbY6K7m8PJBiFyLV1Nv_dhLQyiOtUL38XiagbjFO_p4DNZvu7D1gsswes8sZtbohlD4llpwGX'